### ISSUE TITLE
Toggle doesnt work but copy html does

### ISSUE THREAD

**Issue by josephcc** [Galadirith/markdown-preview-plus#160] opened 2015-12-02 18:59 UTC
I'm running the latest version and i have the markdown-preview disabled, when I try to toggle the preview pane by either ctrl-shift-m or using the command prompt nothing happens. However, copy html works fine.

**Comment by mmstick** [comment] 2015-12-06 01:05
I have the same issue with Arch Linux and the latest stable, although I will also say that the built-in **markdown-preview** plugin doesn't work either -- no preview. Neither plugins work for showing a preview.

**Comment by eljuanchosf** [comment] 2015-12-21 11:09
Same issue here, Linux Mint 17.2. Disabled `markdown-preview`, which didn't toggle, installed `markdown-preview-plus` and it doesn't toggle either.

**Comment by remi-gelinas** [comment] 2015-12-28 05:58
Same issue, OS X 10.11.2. Neither ```markdown-preview``` nor ```markdown-preview-plus``` will open a preview pane.

**Comment by duppypro** [comment] 2015-12-30 08:09
I had the same issue and these steps fixed it for me.

Using Editor: Log Cursor Scope while the cursor was in my README.md file
![Editor: Log Cursor Scope screenshot](https://cloud.githubusercontent.com/assets/1142234/12047965/1e8a6320-ae89-11e5-9410-17d046689493.png)

I found that the scope was text.md and this was not one of the default grammars.

I logged issue #168 

**Work around**:  Set the markdown-preview or markdown-preview-plus Packages -> Settings -> Grammars to text.md or whatever you find with the Editor: Log Cursor Scope command.

![Packages -> Settings -> Grammars screenshot](https://cloud.githubusercontent.com/assets/1142234/12047976/632de812-ae89-11e5-9ae4-114287efa892.png)

**Comment by josephcc** [comment] 2015-12-30 08:34
Guys I just realized my issue was just key binding conflict. Use the conflict resolver to check if thats the case for you, too. You can fix it with custom keybindings. This should be closed.

**Comment by Galadirith** [comment] 2016-03-26 19:35
@josephcc @mmstick @eljuanchosf @remi-gelinas @duppypro Thanks so much for reporting this issue and I really apologise for taking so long to reply to you all. It does look like we have two root causes leading to the same problem.

@josephcc as you've managed to resolve your issue with custom keybindings I will close this issue, but please feel free to post back if you are still having problems.

I will address the fix proposed by @duppypro in #168. Thanks again everyone.

**Closed by Galadirith** 2016-03-26 19:35 UTC
