### ISSUE TITLE
Uncaught TypeError: Cannot read property 'decode' of null

### ISSUE THREAD

**Issue by thecb4** [Galadirith/markdown-preview-plus#100] opened 2015-09-04 11:36 UTC
Attempting to render my report from markdown and getting an error.  

**Atom Version**: 1.0.11
**System**: Mac OS X 10.10.5
**Thrown From**: [markdown-preview-plus](https://github.com/Galadirith/markdown-preview-plus) package, v2.0.1

### Stack Trace

Uncaught TypeError: Cannot read property 'decode' of null

```
At /Users/cavellebenjamin/.atom/packages/markdown-preview-plus/lib/renderer.coffee:114

TypeError: Cannot read property 'decode' of null
  at resolveImagePaths (/Users/cavellebenjamin/.atom/packages/markdown-preview-plus/lib/renderer.coffee:114:23)
  at Function.callbackFunction (/Users/cavellebenjamin/.atom/packages/markdown-preview-plus/lib/renderer.coffee:56:12)
  at handleResponse (/Users/cavellebenjamin/.atom/packages/markdown-preview-plus/lib/pandoc-helper.coffee:133:19)
  at ChildProcess.<anonymous> (/Users/cavellebenjamin/.atom/packages/markdown-preview-plus/node_modules/pdc/pdc.js:65:5)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:169:7)
  at maybeClose (child_process.js:997:16)
  at Process.ChildProcess._handle.onexit (child_process.js:1070:5)

```

### Commands

```
     -3:08.8.0 core:copy (atom-text-editor.editor.is-focused)
  2x -2:55.8.0 editor:newline (atom-text-editor.editor.is-focused)
     -2:55.3.0 core:paste (atom-text-editor.editor.is-focused)
     -2:52.5.0 core:save (atom-text-editor.editor.is-focused)
     -2:38.2.0 run:file (atom-text-editor.editor.is-focused)
     -0:03.7.0 markdown-preview-plus:toggle (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "markdown-preview"
    ]
  },
  "markdown-preview-plus": {
    "breakOnSingleNewline": true,
    "useGitHubStyle": true,
    "enableLatexRenderingByDefault": true,
    "enablePandoc": true
  }
}
```

### Installed Packages

```coffee
# User
atom-jasmine, v0.6.0
atom-runner, v2.4.3
imdone-atom, v1.1.37
language-swift, v0.4.0
linter-swiftc, v2.0.0
markdown-preview-plus, v2.0.1
markdown-table-formatter, v2.5.3
markdown-themeable-pdf, v0.8.0
mathjax-wrapper, v0.1.0
npm, v0.1.0
time-status, v1.1.0
travis-ci-status, v0.17.0

# Dev
No dev packages
```

**Comment by Galadirith** [comment] 2015-09-04 11:41
@thecb4 Thanks so much for the bug report :D It looks like this is a duplicate of #99 and will be patching it shortly.

**Closed by Galadirith** 2015-09-04 11:41 UTC
Labels: bug, duplicate

**Comment by thecb4** [comment] 2015-09-04 11:46
Thanks!!

**Comment by Galadirith** [comment] 2015-09-04 11:49
While we're patching this if you don't need the Pandoc specific features MPP should work fine if you disable Pandoc. However I would imagine you probably do need those features :D Thanks again @thecb4

**Comment by leipert** [comment] 2015-09-04 12:12
@thecb4 :tada: :tanabata_tree: :dancer: Our 100st issue. If you ever make it to Leipzig, Germany or I make it to Atlanta, I will buy you a beer :+1: 

Thanks for using MPP!
