### ISSUE TITLE
Support For Gihub Todo

### ISSUE THREAD

**Issue by yodatak** [Galadirith/markdown-preview-plus#251] opened 2017-01-12 12:52 UTC
Can we support the Github Markdown Todolist its sound like its support in the original ?

**Comment by wedi** [comment] 2017-02-01 23:58
This is a duplicate of #186 and is implemented now. But there is a bug in the rendered preview: https://github.com/Galadirith/markdown-preview-plus/issues/186#issuecomment-276820387

**Comment by lierdakil** [comment] 2017-02-17 00:21
Closing in favor of #186

**Closed by lierdakil** 2017-02-17 00:21 UTC
Labels: enhancement, help wanted
