### ISSUE TITLE
Bug: Preview not displaying in El Capitan

### ISSUE THREAD

**Issue by ondine** [Galadirith/markdown-preview-plus#147] opened 2015-11-09 18:55 UTC
On El Capitan 10.11 Beta … and my Markdown-Preview Plus (Atom 1.1.0) isn't displaying preview...
Installed markdown-preview-plus in Atom's Settings view.
Disabled the built-in package markdown-preview.

**Comment by Galadirith** [comment] 2015-11-10 00:29
@ondine really sorry your experiencing an issue. I'm running Atom 1.1.0 on El Capitan 10.11 right now without any issue, possibly the issue is on the Beta channel?

- Have you previously been able to use MPP on you system?
- What happens when you attempt to open a preview either with `ctrl-shirt-m` or *Packages &rsaquo; Markdown Preview Plus &rsaquo; Toggle Preview*?
- When attempting to open a preview are there any errors generated in dev tools `alt-cmd-i`?

Thanks @ondine.

**Comment by ondine** [comment] 2015-11-10 05:32
I do use MPP on Yosemite and Mavericks, but not yet on El Captain. Strangely it started working for me earlier this afternoon (after I posted the issue). And now again I went back to check and the behavior is the same (not working)... I'm not sure about opening in dev tools...within atom? or on the command line?
![nopreview](https://cloud.githubusercontent.com/assets/3281541/11055171/22ce0a36-8729-11e5-9942-8aec38ec8f41.png)
![previewbutnotext](https://cloud.githubusercontent.com/assets/3281541/11055170/22cad0e6-8729-11e5-99a4-041350abc9a2.png)

**Comment by OJFord** [comment] 2015-11-25 12:38
It works for me on El Capitan.

However, I just now restarted Atom due to problems with the LaTeX rendering, and now it's not rendering LaTeX at all! Ctrl+Shift+X has no effect; nor does choosing the option from the menu.

I still have the standard preview, though, with LaTeX in plaintext.

I'm commenting here instead of creating a new issue, since it seems there is just generally "preview problems on El Capitan".

**Comment by mmstick** [comment] 2015-12-06 01:06
Same thing is happening on Arch Linux. No fix at all though, not even a reboot.

**Comment by harper357** [comment] 2016-01-05 20:00
This is also happening to me. MBP '11, just updated to El Capitan from Mavericks. Toggle worked on Mavericks. Doesn't seem to be working on El Capitan.

**Comment by Galadirith** [comment] 2016-03-26 20:00
@ondine @OJFord @mmstick @harper357 Thanks for reporting this issue and I really apologise for taking so long to reply.

#160 and #168 may both be root causes of problems discussed in this thread. There have been a few updates to both El Capitan and atom since @harper357 last comment. Is anyone still experiencing this problem? I am still unable to reproduce the problem locally running El Capitan 10.11.2. Thanks again everyone.

**Comment by harper357** [comment] 2016-03-27 02:37
I am not sure if it was the same problem or not, but I was recently having this problem after upgrading Atom and managed to fix it (as all the references in #189 describe). As soon as I added the correct grammar files for language-markdown everything seemed to work again.

**Comment by Galadirith** [comment] 2016-03-27 09:57
@harper357 Brilliant, thanks for letting me know. It seems that #189 and other related issues provide a fix, adding `text.md` to the list of grammars. This has been added to the list of default grammars in the recently published `v2.3.0` so this should now be resolved going forward without any user configuration needed.

Thanks again everyone. I will close this issue now, but if you are till experiencing problems related to this issue please post back to this thread.

**Closed by Galadirith** 2016-03-27 09:57 UTC
