### ISSUE TITLE
Compatibility issue with package language-markdown

### ISSUE THREAD

**Issue by Jamesits** [Galadirith/markdown-preview-plus#179] opened 2016-02-01 03:45 UTC
When [`language-markdown`](https://atom.io/packages/language-markdown) is enabled, preview panel doesn't even shows up. 

PS: seems to be an issue like #174 , since right-click on file tree then choose "Markdown Preview" works.

**Comment by nobol** [comment] 2016-02-10 16:40
I can confirm this behavior. This should at least be noted to the README.md, even without fix the users don't get lost (like I did).

**Comment by Bromgard** [comment] 2016-02-21 00:46
The problem might be the same issue mentioned in this thread for Markdown Preview:
https://github.com/burodepeper/language-markdown/issues/51

Just add `text.md` or whatever extension you need to in setting under the Grammars field.

**Comment by Galadirith** [comment] 2016-03-26 23:05
@Jamesits @nobol @Bromgard Thanks so much for reporting this and I really apologise for taking so long to reply.

Thanks @Jamesits for identifying the root cause and @Bromgard for tracking down the assocaited issue in [burodepeper/language-markdown](https://github.com/burodepeper/language-markdown).

This issue seems to be related to #160 and #168 and has now been fixed in 20bebf1 and I will be publishing a release with this fix in it shortly. I really apologise for the problems its caused you in the mean time.

I will close this issue now, but please feel free to post back if you have any other comments related to this issue. Thanks again everyone.

**Closed by Galadirith** 2016-03-26 23:05 UTC
