### ISSUE TITLE
markdown-preview-plus gets blocked when using language-markdown extension

### ISSUE THREAD

**Issue by popas90** [Galadirith/markdown-preview-plus#189] opened 2016-03-20 13:09 UTC
After installing language-markdown extension, markdown-preview-plus does not respond to preview keybinding and I cannot access the preview.

This issue was first filed for fixing in language-markdown:
https://github.com/burodepeper/language-markdown/issues/51

And the fix was actually made in markdown-preview:
https://github.com/atom/markdown-preview/pull/344

Workaround: I was able to use the same solution here by setting the Grammar field to:
`source.gfm, source.litcoffee, text.html.basic, text.plain, text.plain.null-grammar, text.md`

So I'm guessing it's just a matter of adding "text.md" to the default behavior, but I couldn't find where exactly it gets set.

**Comment by Galadirith** [comment] 2016-03-26 23:09
@popas90 Thanks so much for reporting this and I really apologise for taking a week to reply.

Thanks so much for identifying the root cause in burodepeper/language-markdown and tracking down the fix in atom/markdown-preview, really useful stuff.

This issue seems to be related to #160, #168, #174 and #179 and has now been fixed in 20bebf1 and I will be publishing a release with this fix in it shortly. I really apologise for the problems its caused you in the mean time.

I will close this issue now, but please feel free to post back if you have any other comments related to this issue. Thanks again @popas90.

**Closed by Galadirith** 2016-03-26 23:09 UTC

**Comment by popas90** [comment] 2016-03-27 11:44
No problem, thanks for fixing!

Since I had a workaround, it didn't bother me at all and I was able to use markdown-preview-plus just fine.
