### ISSUE TITLE
Can't install plugin

### ISSUE THREAD

**Issue by retorquere** [Galadirith/markdown-preview-plus#10] opened 2014-12-26 21:14 UTC
Atom freshly installed an hour ago; installtion using apm fails. Log at https://gist.github.com/anonymous/8e73ed3e581f41286777

**Comment by AllThatIsTheCase** [comment] 2015-01-02 21:54
Pointing my PATH there first didn't help, nor did running as admin. It looks like a generic SSL error. Perhaps the node guys know; I don't think it's a problem with your addin.

**Comment by Galadirith** [comment] 2015-01-03 00:45
Thanks for letting me know @AllThatIsTheCase and I'm sorry its still a no go. 

At least for the dependencies I added, I don't have to be depending on git repositories directly, it could be tarballs/zips. And all git dependencies look like they actually point at GitHub repos (of course :D). That is a good thing as I should be able to shrinkwrap all dependencies so that they point at tarballs instead of git repos so assuming the problem is with node/git/ssl in some weird combination, this might fix it for you, and wouldnt (shouldnt :D) change the behaviour for anyone else (in fact it might make installation a little quicker).

I'll let you know when I've pushed this change to my repo, and if you feel like it you can clone my repo and test if installation works for you without having to wait for me to push to Atom's package repository :D

**Comment by Galadirith** [comment] 2015-01-11 00:25
@AllThatIsTheCase To update you, I have removed all of my git dependencies in MPP's latests release `v1.0.1`. This may now fix the issue you have been having with installation. Please let me know  if you are now able to install MPP :D

**Comment by AllThatIsTheCase** [comment] 2015-01-11 23:03
Still no dice, sorry: https://gist.github.com/AllThatIsTheCase/b71b7402bc6590d1c023

**Comment by Galadirith** [comment] 2015-01-12 00:11
@AllThatIsTheCase Ah thats a frustrating, im sorry about that. I do notice that the explicit `git` errors have all disappeared though. Can I ask have you had trouble installing any other packages? Also do you have the latest version of python installed, `v2.7.9`?

I'm sure you may have tried this already, but if not could you try running your terminal as an administrator. I would suggest open a terminal with administrative privileges by the following steps:
1. Click start
2. Search for **powershell**
3. Right click **Windows Powershell**
4. Click **Run as administrator**
5. Run `apm install markdown-preview-plus`

**Comment by AllThatIsTheCase** [comment] 2015-01-12 00:33
I haven't had trouble installing other packages. I don't have python installed, is that a prerequisite?

When running PS as admin, I get the same error but with a slight twist; instead of the first ENOENT happening for ...pathwatcher\node_modules\iconv-lite\encodings\tables\cp936.json, it happens for shiftjis.json

**Comment by Galadirith** [comment] 2015-01-12 01:35
So I belive it uses [node-gyp](https://github.com/TooTallNate/node-gyp), which does require python, something I think I should add to the installation instuctions. So I would try installing [Python v2.7.9](https://www.python.org/downloads/release/python-279/) and see how that goes. If that doesn't work try also installing [Microsoft Visual C++ 2010 Redistributable Package (x86)](http://www.microsoft.com/en-gb/download/details.aspx?id=5555). Let me know how it goes :D

**Comment by AllThatIsTheCase** [comment] 2015-01-31 21:03
Python helped, but then it also needed the .NET Framework 2.0 SDK according to the error the installer threw. I'm having some issues installing that SDK though. Will keep you posted.

**Comment by Galadirith** [comment] 2015-01-31 22:17
@AllThatIsTheCase, im glad it made at least some difference, and just really sorry its taking so long to resolve this issue for you. One recent issue Galadirith/markdown-preview-plus#16 also had problems with the .NET framework, and was fixed by installing [Visual C++ 2010 Express](http://www.visualstudio.com/en-us/downloads/download-visual-studio-vs#DownloadFamilies_4). Please have a read of the [comments](https://github.com/Galadirith/markdown-preview-plus/issues/16#issuecomment-72006064) I made.

As always please let me know if you need any help and let me know how it goes :D

**Comment by AllThatIsTheCase** [comment] 2015-02-01 13:14
Hi @Galadirith; I appreciate your stick-to-it-ness, but I have to draw the line at installing a full IDE. I realize fully this is not something you opted for, just that node-shell perhaps isn't a mature product on Windows, and I'm running this on a space-constrained system (a surface pro).

**Comment by Galadirith** [comment] 2015-02-01 13:55
@AllThatIsTheCase, of course I completely understand. If I do find any further details that suggest a fix without needing to install VC++ IDE I will update you :D 

(Just as a correction to a previous comment, as your using a surface pro I assume your running windows 8, so should you change your mind you would need [Microsoft Visual Studio C++ 2013 Express for Windows Desktop](http://www.visualstudio.com/en-us/products/visual-studio-express-vs.aspx))

**Closed** 2015-05-10 12:52 UTC
Labels: help wanted
