### ISSUE TITLE
Add scroll-sync

### ISSUE THREAD

**Issue by exside** [Galadirith/markdown-preview-plus#256] opened 2017-02-03 12:13 UTC
same thing as this package does, but it doesn't work for markdown-preview-plus, only for the default one: https://atom.io/packages/markdown-scroll-sync

**Comment by lierdakil** [comment] 2017-02-05 12:28
Mpp should, at least in theory, be supported by that package, at least
looking at the source code. And I distinctly remember that it did work for
me at some point (although it didn't always scroll where appropriate, so if
you can call that 'working')

пт, 3 февр. 2017 г., 15:13 Lukas Zahnd <notifications@github.com>:

same thing as this package does, but it doesn't work for
markdown-preview-plus, only for the default one:
https://atom.io/packages/markdown-scroll-sync

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Galadirith/markdown-preview-plus/issues/256>, or mute
the thread

**Comment by lierdakil** [comment] 2017-02-08 09:47
Closing as duplicate of #9.

**Closed by lierdakil** 2017-02-08 09:47 UTC
Labels: duplicate
