### ISSUE TITLE
In preview, README.md is autolinked to someone's README.md on Github

### ISSUE THREAD

**Issue by dgoppenheimer** [Galadirith/markdown-preview-plus#139] opened 2015-10-15 21:35 UTC
I'm using markdown-preview-plus (v 2.2.1 in Atom 1.0.19 and I refer to a README.md file in a markdown document. In the preview generated by markdown-preview-plus, the README.md file is linked to https://github.com/echonest/pyechonest/blob/master/README.md even though I have not included this link in the original markdown document. How can I unlink this?

**Comment by dgoppenheimer** [comment] 2015-10-16 16:36
I have updated to markdown-preview-plus v 2.2.2 in Atom 1.0.19, and the problem persists. To reproduce the problem:
1. Open Atom.
2. Create a new file (File > New File).
3. Add some text:
   ```
   # Heading 1
   
   more text. Here is the file, readme.md.
   Here is the file, README.md.
   ```
4. Go to Packages > Markdown Preview Plus > Toggle Preview to open preview pane.
5. Both the readme.md and the README.md files are linked to https://github.com/echonest/pyechonest/blob/master/README.md.

**Comment by Galadirith** [comment] 2015-11-01 23:16
@dgoppenheimer Thanks for raising this issue, and I really apologise for not having been able to reply to you sooner.

So the cause of this is because our markdown parser [`markdown-it`](https://github.com/markdown-it/markdown-it) automatically converts any url like expression to hyperlinks. It turns out that the URL [`readme.md`](https://github.com/echonest/pyechonest/blob/master/README.md) simply points at https://github.com/echonest/pyechonest/blob/master/README.md.

As a temporary measure to correct this issue, you can change line 31 of [`lib/markdown-it-helper.coffee`](https://github.com/Galadirith/markdown-preview-plus/blob/12432cba6c827b24eb60da3f73bbd0b28594df14/lib/markdown-it-helper.coffee#L31) from:
````coffeescript
  linkify: true
````
to
````coffeescript
  linkify: false
````

Long term we can fix this by adding an entry to our settings page to configure this option to automatically create a hyperlink out of url like strings. I can't give you a date as to when this feature will be released, but its a simple fix so most likely in our next release. I'll make sure to keep you updated on its progress. 

Please let me know if you have any other questions, thanks again @dgoppenheimer.

**Comment by dgoppenheimer** [comment] 2015-11-02 04:46
Dear Edward,

Thank you for the reply, and for the work-around. I will try it and let 
you know if I have any further problems.

Also, thank you for writing this package. I find it really useful as I 
switch more of my writing to markdown.

best wishes,
David

> Edward Fauchon-Jones <mailto:notifications@github.com>
> November 1, 2015 at 6:16 PM
>
> @dgoppenheimer <https://github.com/dgoppenheimer> Thanks for raising 
> this issue, and I really apologise for not having been able to reply 
> to you sooner.
>
> So the cause of this is because our markdown parser |markdown-it| 
> <https://github.com/markdown-it/markdown-it> automatically converts 
> any url like expression to hyperlinks. It turns out that the URL 
> |readme.md| 
> <https://github.com/echonest/pyechonest/blob/master/README.md> simply 
> points at https://github.com/echonest/pyechonest/blob/master/README.md.
>
> As a temporary measure to correct this issue, you can change line 31 
> of |lib/markdown-it-helper.coffee| 
> <https://github.com/Galadirith/markdown-preview-plus/blob/12432cba6c827b24eb60da3f73bbd0b28594df14/lib/markdown-it-helper.coffee#L31> 
> from:
>
> linkify: true
>
> to
>
> linkify: false
>
> Long term we can fix this by adding an entry to our settings page to 
> configure this option to automatically create a hyperlink out of url 
> like strings. I can't give you a date as to when this feature will be 
> released, but its a simple fix so most likely in our next release. 
> I'll make sure to keep you updated on its progress.
>
> Please let me know if you have any other questions, thanks again 
> @dgoppenheimer <https://github.com/dgoppenheimer>.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/Galadirith/markdown-preview-plus/issues/139#issuecomment-152874411>.
>

-- 
David G. Oppenheimer

email: dg.oppenheimer@gmail.com
websites: http://undergradinthelab.com
http://people.clas.ufl.edu/oppenhe/

**Closed** 2017-02-17 14:26 UTC
Labels: enhancement
