### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by clbarnes** [Galadirith/markdown-preview-plus#174] opened 2016-01-21 15:12 UTC
I know that's a really unhelpful issue title, but I don't know how else to explain it.

Ubuntu 15.10, atom installed from the website .deb file on 01/21/15. I disabled markdown-preview as per the readme, installed and enabled markdown-preview-plus. The key binding is enabled, but doesn't open a preview tab.

I thought it might be ubuntu stealing one of my keys, so I changed it in the keymap.cson; still nothing.

**Comment by edwinksl** [comment] 2016-01-24 07:01
I can confirm the package doesn't work on Ubuntu 15.10 with both Atom 1.4.0 and 1.5.0.

**Comment by jneubrand** [comment] 2016-01-27 17:39
I've also encountered this issue on Atom 1.4.1. Copying HTML works, but preview tabs aren't opened. The console doesn't log anything.

**Comment by jneubrand** [comment] 2016-01-27 17:46
Ok, looks like there's a silver lining: right-clicking on a file in the tree view and selecting "Markdown Preview" works! I'm assuming your code for detecting whether the file is already being previewed is broken.

**Comment by teoric** [comment] 2016-02-15 18:12
Well, I think the silver lining is a Fata Morgana: This seems to be the normal Markdown Preview, not the plus version, for even if I enable Pandoc in markdown-preview-plus, none of the Pandoc features is used (citation parsing, metadata header, numbered examples etc.).

**Comment by clbarnes** [comment] 2016-03-25 18:55
I'm on 1.6.0 and it still suffers from the same problem. Right click -> Markdown Preview does bring up the preview, so it's really just the keyboard shortcut and the Packages -> Markdown Preview Plus -> Toggle etc. which don't work.

**Comment by Galadirith** [comment] 2016-03-26 23:02
@clbarnes @edwinksl @jneubrand @teoric Thanks so much for reporting this and I really apologise for taking so long to reply.

This issue seems to be related to #160 and #168 and has now been fixed in 20bebf1 and I will be publishing a release with this fix in it shortly. I really apologise for the problems its caused you in the mean time.

I will close this issue now, but please feel free to post back if you have any other comments related to this issue. Thanks again everyone.

**Closed by Galadirith** 2016-03-26 23:02 UTC
