### ISSUE TITLE
Leading spaces in the first line of backtick or fenced code blocks are missing

### ISSUE THREAD

**Issue by hanwentao** [Galadirith/markdown-preview-plus#165] opened 2015-12-16 02:29 UTC
Code like

```
  hello
  world
```

is rendered incorrectly by Markdown Plus.  The leading spaces in the first line are missing.

**Comment by chrahunt** [comment] 2016-03-06 16:38
Reproduced on MPP 2.2.2, Atom 1.5.4. This is the same problem as in atom/markdown-preview#360 and it looks like with the same cause. The renderer trims the text of code blocks [here](https://github.com/Galadirith/markdown-preview-plus/blob/master/lib/renderer.coffee#L138) which removes the leading whitespace. Why is that trim there?

**Comment by Galadirith** [comment] 2016-03-31 13:12
@hanwentao @chrahunt Thanks so much to both of you for catching this and I really apologise for taking so long to reply.

So the `.trim()` was inherited when forking [`markdown-preview`](https://github.com/atom/markdown-preview) and I never gave it much thought, as you say it doesn't make sense; pre-formated code should be render as whatever the user wrote, whitespace and all.

However I can speculate on why this `.trim()` was added to the preview ([`renderer.coffee#L138`](https://github.com/Galadirith/markdown-preview-plus/blob/1292e71565f76cfeb3ce38ff6c42f2976ea1d83d/lib/renderer.coffee#L138)) but not when saving as HTML ([`renderer.coffee#L156`](https://github.com/Galadirith/markdown-preview-plus/blob/1292e71565f76cfeb3ce38ff6c42f2976ea1d83d/lib/renderer.coffee#L156)).

Taking the example of

    ```
    hello, world
    ```

is parsed by out markdown parser to

```
<pre><code>hello, world\n</code></pre>\n
```

The saved HTML which is parse through `highlights` ends up looking like
```
 <pre class="editor-colors lang-text"><div class="line"><span class="text plain"><span class="meta paragraph text"><span>hello,&nbsp;world</span></span></span></div></pre>
```
which loose all `\n` in favour of `<div>`'s delimiting lines. In particular the `\n` after the `world` does not cause an extra new line to be created.

The preview however converts the code block into an `<atom-text-editor>` which does interpret the trailing `\n` after `world` as an extra line. This would mean that all fenced code blocks would have an extra newline in the preview.

So the solution I believe is to replace `.trim()` with `.replace(/\n$/,'')` that will strip the trailing newline, but leave any other whitespace on the leading or trailing edges. I would speculate that the `.trim()` was added to solve this problem but the other issues (like this one) were not for seen at the time.

I'll patch this shortly and publish a new release shortly after that. I will let you know when this is done. Thanks again @hanwentao @chrahunt

**Comment by Galadirith** [comment] 2016-03-31 14:15
For future reference W3 has this to say about newline characters around `pre` tags

> Note: In [the HTML syntax](https://www.w3.org/TR/html5/syntax.html#syntax), a leading newline character immediately following the [`pre`](https://www.w3.org/TR/html5/grouping-content.html#the-pre-element) element start tag is stripped.
>
> \- [4.4.3 The pre element](https://www.w3.org/TR/html5/grouping-content.html#the-pre-element)

Test in chrome suggest that a newline character preceding the closing `pre` tag is also stripped. However in the case of this issue I don't believe the `pre` spec is causing this problem.

**Closed** 2016-03-31 22:57 UTC
