### ISSUE TITLE
Cannot make it works in windows 8.1 x64

### ISSUE THREAD

**Issue by mhnavarro** [Galadirith/markdown-preview-plus#25] opened 2015-02-15 04:48 UTC
Hi, I got this error when I try to install the package.

Python 2.7.9 installed
MS VC++ express 2010 installed

```
PS C:\Windows\System32\WindowsPowerShell\v1.0> apm install markdown-preview-plus
Installing markdown-preview-plus to C:\Users\Marco\.atom\packages failed

> runas@2.0.0 install C:\Users\Marco\AppData\Local\Temp\apm-install-dir-115114-8580-lyx6r1\node_modules\markdown-previe
-plus\node_modules\pathwatcher\node_modules\runas
> node-gyp rebuild


C:\Users\Marco\AppData\Local\Temp\apm-install-dir-115114-8580-lyx6r1\node_modules\markdown-preview-plus\node_modules\pa
hwatcher\node_modules\runas>node "C:\Users\Marco\AppData\Local\atom\app-0.179.0\resources\app\apm\node_modules\npm\bin\
ode-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild

> oniguruma@4.0.0 install C:\Users\Marco\AppData\Local\Temp\apm-install-dir-115114-8580-lyx6r1\node_modules\markdown-pr
view-plus\node_modules\highlights\node_modules\first-mate\node_modules\oniguruma
> node-gyp rebuild


C:\Users\Marco\AppData\Local\Temp\apm-install-dir-115114-8580-lyx6r1\node_modules\markdown-preview-plus\node_modules\hi
hlights\node_modules\first-mate\node_modules\oniguruma>node "C:\Users\Marco\AppData\Local\atom\app-0.179.0\resources\ap
\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild

gypgypnpm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\Users\\Marco\\AppData\\Local\\atom\\app-0.179.0\\resources\\app\\apm\\bin\\\\node.exe" "C:\\Users\\M
rco\\AppData\\Local\\atom\\app-0.179.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\
sers\\Marco\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\Marco\\.atom\\.apmrc" "install" "C:\\Users\\Marco\\AppData
\Local\\Temp\\d-115114-8580-1h7nvcc\\package.tgz" "--target=0.21.0" "--arch=ia32" "--msvs_version=2013"
npm ERR! node v0.10.35
npm ERR! npm  v2.3.0
npm ERR! code ELIFECYCLE

npm ERR! runas@2.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the runas@2.0.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the runas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls runas
npm ERR! There is likely additional logging output above.
```

I was reading some other threads and it looks like it needs to use msvs_version=2010 but i don´t know how to change it.

Any help would be appreciated.

I would really like to use this package.

**Comment by Galadirith** [comment] 2015-02-24 23:11
@arkandoscr I really want to apologise for not having been able to respond to you sooner. Hopefully we can help you get the package working for you quickly :D 

So yes `msvs_version=2010` might well fix it. If you want to use your currently installed version of VC++ then you can open up powershell (if you can open it as an administrator just to be safe) and run: 

````bash
apm install markdown-preview-plus --msvs_version=2010
````

Now hopefully that will work. If using `msvs_version=2010` doesn't work its likely you will need to install the 2013 edition, which you can get at [Visual Studio Community & Express](http://www.visualstudio.com/en-us/downloads/download-visual-studio-vs#DownloadFamilies_2) and click on the *Express 2013 with Update 4 for Windows Desktop* option.

Do please let me know how it goes and if you have any problem with any of my instructions :D (I saw that you also had problems with izuzak/atom-pdf-view#50. Hopefully if we get my package running for you it will also resolve that issue too :D)

**Comment by mhnavarro** [comment] 2015-03-05 21:31
Hi @Galadirith it's me @arkandoscr, i had to change the username. 
Thanks for your help, but problem persist. It seems like the ```--msvs_version=2010``` parameter is not been recognized by apm. See log.

```
C:\Windows\System32>apm install markdown-preview-plus --msvs_version=2010
Installing markdown-preview-plus to C:\Users\marco_2\.atom\packages failed

> runas@2.0.0 install C:\Users\marco_2\AppData\Local\Temp\apm-install-dir-11525-
6600-ys39ql\node_modules\markdown-preview-plus\node_modules\pathwatcher\node_mod
ules\runas
> node-gyp rebuild


C:\Users\marco_2\AppData\Local\Temp\apm-install-dir-11525-6600-ys39ql\node_modul
es\markdown-preview-plus\node_modules\pathwatcher\node_modules\runas>node "C:\Us
ers\marco_2\AppData\Local\atom\app-0.177.0\resources\app\apm\node_modules\npm\bi
n\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
Los proyectos de esta soluci�n se van a compilar de uno en uno. Para habilitar l
a compilaci�n en paralelo, agregue el modificador "/m".
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppBuild.target
s(396,5): warning MSB8029: The Intermediate directory or Output directory cannot
 reside under the Temporary directory as it could lead to issues with incrementa
l build. [C:\Users\marco_2\AppData\Local\Temp\apm-install-dir-11525-6600-ys39ql\
node_modules\markdown-preview-plus\node_modules\pathwatcher\node_modules\runas\b
uild\runas.vcxproj]
  main.cc
  runas_win.cc
C:\Program Files (x86)\Windows Kits\8.1\Include\um\winsock2.h(882): fatal error
C1083: Cannot open include file: 'qos.h': No such file or directory (..\src\main
.cc) [C:\Users\marco_2\AppData\Local\Temp\apm-install-dir-11525-6600-ys39ql\node
_modules\markdown-preview-plus\node_modules\pathwatcher\node_modules\runas\build
\runas.vcxproj]

> oniguruma@4.0.0 install C:\Users\marco_2\AppData\Local\Temp\apm-install-dir-11
525-6600-ys39ql\node_modules\markdown-preview-plus\node_modules\highlights\node_
modules\first-mate\node_modules\oniguruma
> node-gyp rebuild


C:\Users\marco_2\AppData\Local\Temp\apm-install-dir-11525-6600-ys39ql\node_modul
es\markdown-preview-plus\node_modules\highlights\node_modules\first-mate\node_mo
dules\oniguruma>node "C:\Users\marco_2\AppData\Local\atom\app-0.177.0\resources\
app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-
gyp.js" rebuild
Los proyectos de esta soluci�n se van a compilar de uno en uno. Para habilitar l
a compilaci�n en paralelo, agregue el modificador "/m".
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppBuild.target
s(396,5): warning MSB8029: The Intermediate directory or Output directory cannot
 reside under the Temporary directory as it could lead to issues with incrementa
l build. [C:\Users\marco_2\AppData\Local\Temp\apm-install-dir-11525-6600-ys39ql\
node_modules\markdown-preview-plus\node_modules\highlights\node_modules\first-ma
te\node_modules\oniguruma\build\oniguruma.vcxproj]
  regcomp.c
  regenc.c
  regerror.c
  regexec.c
  regext.c
  reggnu.c
  regparse.c
  regposerr.c
  regposix.c
  regsyntax.c
  regtrav.c
  regversion.c
  st.c
  ascii.c
  big5.c
  cp1251.c
  euc_jp.c
  euc_kr.c
  euc_tw.c
  gb18030.c
  iso8859_1.c
  iso8859_2.c
  iso8859_3.c
  iso8859_4.c
  iso8859_5.c
  iso8859_6.c
  iso8859_7.c
  iso8859_8.c
  iso8859_9.c
  iso8859_10.c
  iso8859_11.c
  iso8859_13.c
  iso8859_14.c
  iso8859_15.c
  iso8859_16.c
  koi8.c
  koi8_r.c
  mktable.c
  sjis.c
  unicode.c
  utf16_be.c
..\deps\onig\enc\mktable.c(265): warning C4028: formal parameter 1 different fro
m declaration [C:\Users\marco_2\AppData\Local\Temp\apm-install-dir-11525-6600-ys
39ql\node_modules\markdown-preview-plus\node_modules\highlights\node_modules\fir
st-mate\node_modules\oniguruma\build\oniguruma.vcxproj]
  utf16_le.c
  utf32_be.c
  utf32_le.c
  utf8.c
  oniguruma.vcxproj -> C:\Users\marco_2\AppData\Local\Temp\apm-install-dir-11525
-6600-ys39ql\node_modules\markdown-preview-plus\node_modules\highlights\node_mod
ules\first-mate\node_modules\oniguruma\build\Release\\oniguruma.lib
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppBuild.target
s(396,5): warning MSB8029: The Intermediate directory or Output directory cannot
 reside under the Temporary directory as it could lead to issues with incrementa
l build. [C:\Users\marco_2\AppData\Local\Temp\apm-install-dir-11525-6600-ys39ql\
node_modules\markdown-preview-plus\node_modules\highlights\node_modules\first-ma
te\node_modules\oniguruma\build\onig_scanner.vcxproj]
  onig-cache.cc
  onig-result.cc
  onig-reg-exp.cc
  onig-scanner.cc
C:\Program Files (x86)\Windows Kits\8.1\Include\um\winsock2.h(882): fatal error
C1083: Cannot open include file: 'qos.h': No such file or directory (..\src\onig
-reg-exp.cc) [C:\Users\marco_2\AppData\Local\Temp\apm-install-dir-11525-6600-ys3
9ql\node_modules\markdown-preview-plus\node_modules\highlights\node_modules\firs
t-mate\node_modules\oniguruma\build\onig_scanner.vcxproj]
  onig-scanner-worker.cc
  onig-searcher.cc
  unicode-utils-win.cc
C:\Program Files (x86)\Windows Kits\8.1\Include\um\winsock2.h(882): fatal error
C1083: Cannot open include file: 'qos.h': No such file or directory (..\src\onig
-scanner.cc) [C:\Users\marco_2\AppData\Local\Temp\apm-install-dir-11525-6600-ys3
9ql\node_modules\markdown-preview-plus\node_modules\highlights\node_modules\firs
t-mate\node_modules\oniguruma\build\onig_scanner.vcxproj]
C:\Program Files (x86)\Windows Kits\8.1\Include\um\winsock2.h(882): fatal error
C1083: Cannot open include file: 'qos.h': No such file or directory (..\src\onig
-scanner-worker.cc) [C:\Users\marco_2\AppData\Local\Temp\apm-install-dir-11525-6
600-ys39ql\node_modules\markdown-preview-plus\node_modules\highlights\node_modul
es\first-mate\node_modules\oniguruma\build\onig_scanner.vcxproj]

gypgypnpm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\Users\\marco_2\\AppData\\Local\\atom\\app-0.177.0\\resources\
\app\\apm\\bin\\\\node.exe" "C:\\Users\\marco_2\\AppData\\Local\\atom\\app-0.177
.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C
:\\Users\\marco_2\\AppData\\Local\\atom\\app-0.177.0\\resources\\app\\apm\\.apmr
c" "--userconfig" "C:\\Users\\marco_2\\.atom\\.apmrc" "install" "C:\\Users\\marc
o_2\\AppData\\Local\\Temp\\d-11525-6600-17rpb9e\\package.tgz" "--target=0.21.0"
"--arch=ia32" "--msvs_version=2013"
npm ERR! node v0.10.35
npm ERR! npm  v2.3.0
npm ERR! code ELIFECYCLE

npm ERR! runas@2.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the runas@2.0.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the runas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls runas
npm ERR! There is likely additional logging output above.

```

**Comment by Galadirith** [comment] 2015-03-08 23:12
@mhnavarro thanks for letting me know about the name change :D I'm really sorry the problem still persists.

So I do believe that the problem is that you don't have VS 2013 installed. If you take a look about 16 lines up from the bottom of your last log it says `--msvs_version=2013` which obviously isn't the version you asked it to use, so as you said it clearly isn't respecting your input, or at the very least part of the installation isn't.

I'll try to dig into this a little more but I think that it is likely that [node-gyp](https://github.com/TooTallNate/node-gyp)  (that is the bit I belive to be causing the problem) simply needs 2013 on Windows 8 regardless of the option you give it.

If you can I would suggest installing VS 2013, you can get hold of [Visual Studio Community & Express](https://www.visualstudio.com/en-us/downloads/download-visual-studio-vs#DownloadFamilies_2); you'll want to and click on the *Express 2013 with Update 4 for Windows Desktop option*.

Let me know if you need any further help or have any other questions, Im sorry that I can't suggest anything other than installing another programme at the moment.

I also apologise in advanced, i'll be away for the next 2 weeks so I might be unable to msg you back immediately. Thanks again @mhnavarro

**Comment by mhnavarro** [comment] 2015-03-23 01:39
Hi, I tried to solve it myself and.... I couldn't.
I installed VS 2013 but it doesn't seem to be the problem. 

Looking the log file there a thing that looks suspicious.

```
C:\Program Files (x86)\Windows Kits\8.1\Include\um\winsock2.h(882): fatal error
C1083: Cannot open include file: 'qos.h': No such file or directory (..\src\main
.cc) [C:\Users\marco_2\AppData\Local\Temp\apm-install-dir-11525-6600-ys39ql\node
_modules\markdown-preview-plus\node_modules\pathwatcher\node_modules\runas\build
\runas.vcxproj]
```

That file exist in my windows installation, however the compiler can't find it.

Is there a way to provide a path to a libraries folder in the apm command?

**Comment by cbuschardt** [comment] 2015-03-25 01:19
I'm having a very similar issue here.  I'd love to work with you to get this resolved!

Is it possible to separate markdown-preview-plus from any dependence on oniguruma?  What exactly is it being used for? I note that markdown-preview installs correctly, so they either don't have this dependence -- or found a way to disable it.

Meanwhile, I set the GYP_... build variables to contain the direct path to my Visual Studio install path and received the following error.  I've checked and libcpmt.lib is the correct name, presumably something is wrong with the vcxproj that oniguruma uses.  More later.

  unicode-utils-win.cc
LINK : fatal error LNK1104: cannot open file 'libcpmt.lib' [C:\Users\Cameron\AppData\Local\Temp\apm-install-dir-115224-11604-x1xj7v\node_modules\markdown-preview-plus\node_modules\highlights\node_modules\first-mate\node_modules\oniguruma\build\onig_scanner.vcxproj]

**Comment by Galadirith** [comment] 2015-05-06 22:36
Hey @mhnavarro. Can I first apologise for my really long absence.

I've just pushed a long overdue version that should solve the majority of issue that have popped up over the last couple of months as MPP fell behind atom's progress. Now this new version may or may not solve the problems you have been having.

@mhnavarro @cbuschardt please let me know if you still are having problems and we can take it from their :D

**Comment by cbuschardt** [comment] 2015-05-06 23:35
I will definitely give it a shot!  
 
Thanks for the *great* work on this plugin =)
 
-Cameron
 
Date: Wed, 6 May 2015 15:36:31 -0700

**Comment by magic2k** [comment] 2015-05-20 15:25
https://msdn.microsoft.com/en-us/library/windows/desktop/bg162891.aspx

**Comment by Galadirith** [comment] 2015-07-09 17:23
@mhnavarro @cbuschardt I hope that MPP is now installing for you and thanks @magic2k for the helpful link. As its been over a month since the last comment I'm closing the issue, but if anyone is still experiencing the issue please post back and I would be more than happy to look into it further :D

**Closed by Galadirith** 2015-07-09 17:23 UTC
Labels: help wanted
